### ISSUE TITLE
Reversed bit order / EDIF in Yosys

### ISSUE THREAD

**Issue by peterzieba** [hoglet67/atf15xx_yosys#2]
Hi,

I came across this which suggests that this might have been fixed but never merged?
https://github.com/YosysHQ/yosys/pull/830

This is related to issue #568 and reverse bit order in the generated EDIF.

**Comment by hoglet67** [comment]
I'm currently working around this issue with some post-processing of the EDIF in a script:
https://github.com/hoglet67/atf15xx_yosys/blob/609d70fe6b26644ff4e91c483dd09c8f2e4f9210/run_yosys.sh#L46

**Comment by peterzieba** [comment]
I nudged the following ticket https://github.com/YosysHQ/yosys/pull/1489 which ended up getting merged into yosys master.

In theory, one can now do `write_edif -lsbidx`

I haven't yet had a chance to test this, but I think this might resolve things...

**Comment by hoglet67** [comment]
Thanks for nudging this issue Peter. I've just tested the write_edif -lsbidx option and it seems very much equivalent to ugly the perl hack I had in place. The fitter output is identical. So I've updated the run_yosys script to use this option if it's available.
